apiVersion: v1
kind: Secret
metadata:
    name: docker-hub-creds
    annotations:
        build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data:
    username: REPLACE_WITH_YOUR_BASE64_USERNAME
    password: REPLACE_WITH_YOUR_BASE64_PASSWORD
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: knative-builder-nuweba
secrets:
    - name: docker-hub-creds